// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations / introspection use the DIRECT connection (port 5432), not the
    // pgbouncer pooler, which can't run DDL reliably.
    url: process.env["DIRECT_URL"],
  },
});
